// <auto-generated />
using System;
using DeveloperPortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperPortalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531203553_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperPortalApi.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2453fe8c-5de2-42cf-a393-e25ab7561832"),
                            Message = "Hey developer, leuk dat je er bent!",
                            MessageTime = new DateTimeOffset(new DateTime(2024, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Username = "Matthijs Meijboom",
                            auth0Id = "google-oauth2|112201690251789498274"
                        },
                        new
                        {
                            Id = new Guid("6540898b-c70c-4625-9a01-92d437be9002"),
                            Message = "Hey developer!!",
                            MessageTime = new DateTimeOffset(new DateTime(2024, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Username = "Developer",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        });
                });

            modelBuilder.Entity("DeveloperPortalApi.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aca74b08-d1c1-4c48-a17e-77b0e03b0ece"),
                            Content = "Applicatie afmaken!",
                            Username = "Developer",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        },
                        new
                        {
                            Id = new Guid("727ceb19-d2ab-47ce-9a28-9acde3475c43"),
                            Content = "Demo voorbereiden!",
                            Username = "Matthijs Meijboom",
                            auth0Id = "google-oauth2|112201690251789498274"
                        });
                });

            modelBuilder.Entity("DeveloperPortalApi.Entities.PokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PokerVotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c6d7539-632f-4f1f-ad2e-d7e145c84ec5"),
                            Username = "Matthijs Meijboom",
                            Vote = "☕",
                            auth0Id = "google-oauth2|112201690251789498274"
                        },
                        new
                        {
                            Id = new Guid("2d601ffb-69a4-4317-a1d7-33a0d2fd4908"),
                            Username = "Developer",
                            Vote = "8",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
