// <auto-generated />
using System;
using DeveloperPortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperPortalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperPortalApi.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e599efb5-b943-4f8f-893f-2d8bc6f82d61"),
                            Message = "Hey developer, leuk dat je er bent!",
                            MessageTime = new DateTimeOffset(new DateTime(2024, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Username = "Matthijs Meijboom",
                            auth0Id = "google-oauth2|112201690251789498274"
                        },
                        new
                        {
                            Id = new Guid("09806674-62db-428a-8aa2-669c18268b82"),
                            Message = "Hey developer!!",
                            MessageTime = new DateTimeOffset(new DateTime(2024, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Username = "Developer",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        });
                });

            modelBuilder.Entity("DeveloperPortalApi.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bc63911-27d2-4bc4-94f2-22b4d45ffd8a"),
                            Content = "Applicatie afmaken!",
                            Username = "Developer",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        },
                        new
                        {
                            Id = new Guid("fc7b557f-1728-48c1-8da0-816d514d53df"),
                            Content = "Demo voorbereiden!",
                            Username = "Matthijs Meijboom",
                            auth0Id = "google-oauth2|112201690251789498274"
                        });
                });

            modelBuilder.Entity("DeveloperPortalApi.Entities.PokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PokerVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
