// <auto-generated />
using System;
using DeveloperPortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperPortalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperPortalApi.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4acd9839-f289-47f4-8a3f-942edbb68d46"),
                            Message = "Hey developer, leuk dat je er bent!",
                            MessageTime = new DateTimeOffset(new DateTime(2024, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Username = "Matthijs Meijboom",
                            auth0Id = "google-oauth2|112201690251789498274"
                        },
                        new
                        {
                            Id = new Guid("053624f5-8e03-4058-825c-5f4b0472b18b"),
                            Message = "Hey developer!!",
                            MessageTime = new DateTimeOffset(new DateTime(2024, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Username = "Developer",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        });
                });

            modelBuilder.Entity("DeveloperPortalApi.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("089cbe48-48b1-4a47-8f8d-54ad8af2d432"),
                            Content = "Applicatie afmaken!",
                            Username = "Developer",
                            auth0Id = "auth0|661834a129d6402ebd9baa0c"
                        },
                        new
                        {
                            Id = new Guid("b2536b41-af56-47a0-a47a-143eb518f0b9"),
                            Content = "Demo voorbereiden!",
                            Username = "Matthijs Meijboom",
                            auth0Id = "google-oauth2|112201690251789498274"
                        });
                });

            modelBuilder.Entity("DeveloperPortalApi.Entities.PokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PokerVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
